In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

In [3]:
import numpy as np

In [4]:
a=[[1,5,8],[9,3,6]]
a

[[1, 5, 8], [9, 3, 6]]

In [5]:
b=np.array(a)

In [6]:
b

array([[1, 5, 8],
       [9, 3, 6]])

In [8]:
type(b)

numpy.ndarray

In [13]:
L1=list(range(1000000))
L2=list(range(1000000))

In [9]:
b.shape

(2, 3)

In [11]:
A1=np.arange(100000)
A2=np.arange(100000)

In [15]:
import time
start =time.time()
L3=list(map(lambda x,y:x+y,L1,L2))
end=time.time()
print((end-start)*1000)
print(f'time taken is{((end-start)*1000)} millisecond')

487.6976013183594
time taken is487.6976013183594 millisecond


In [23]:
import time
start=time.time()
A3=A1+A2
end=time.time()
print((end-start)*1000)
print(f'time taken is{((end-start)*1000)}millisecond')

0.0
time taken is0.0millisecond


In [24]:
a=np.array([[1,5,6],[8,9,5],[2,6,6]])

In [25]:
a

array([[1, 5, 6],
       [8, 9, 5],
       [2, 6, 6]])

In [26]:
a.shape

(3, 3)

In [27]:
a.size

9

In [28]:
a[0]

array([1, 5, 6])

In [29]:
a[1,1]

9

In [30]:
a[2,2]

6

In [31]:
a[2,0]

2

In [32]:
a[2][0]

2

In [38]:
a[1:,1:]

array([[9, 5],
       [6, 6]])

In [41]:
a[1:,0:2]

array([[8, 9],
       [2, 6]])

In [42]:
a[1:,:2]

array([[8, 9],
       [2, 6]])

In [47]:
b=np.array([[2,5,8],[5,6,-3],[8,9,6]])

In [48]:
b

array([[ 2,  5,  8],
       [ 5,  6, -3],
       [ 8,  9,  6]])

In [49]:
a

array([[1, 5, 6],
       [8, 9, 5],
       [2, 6, 6]])

In [50]:
a+b

array([[ 3, 10, 14],
       [13, 15,  2],
       [10, 15, 12]])

In [51]:
a-b

array([[-1,  0, -2],
       [ 3,  3,  8],
       [-6, -3,  0]])

In [52]:
a*b

array([[  2,  25,  48],
       [ 40,  54, -15],
       [ 16,  54,  36]])

In [53]:
a/b

array([[ 0.5       ,  1.        ,  0.75      ],
       [ 1.6       ,  1.5       , -1.66666667],
       [ 0.25      ,  0.66666667,  1.        ]])

In [54]:
a//b

array([[ 0,  1,  0],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [55]:
np.add(a,b)

array([[ 3, 10, 14],
       [13, 15,  2],
       [10, 15, 12]])

In [56]:
np.subtract(a,b)

array([[-1,  0, -2],
       [ 3,  3,  8],
       [-6, -3,  0]])

In [57]:
np.mean(a)

5.333333333333333

In [63]:
np.mean(a,axis=0)#columnwise 

array([3.66666667, 6.66666667, 5.66666667])

In [59]:
a/3

array([[0.33333333, 1.66666667, 2.        ],
       [2.66666667, 3.        , 1.66666667],
       [0.66666667, 2.        , 2.        ]])

In [60]:
np.median(a)

6.0

In [65]:
np.mean(a,axis=1)#row wise1+5+6/3

array([4.        , 7.33333333, 4.66666667])

In [64]:
np.var(a)

5.777777777777778

In [67]:
np.var(a,axis=0)

array([9.55555556, 2.88888889, 0.22222222])

In [68]:
np.var(a,axis=1)

array([4.66666667, 2.88888889, 3.55555556])

In [69]:
np.std(a)

2.4037008503093262

In [70]:
np.max(a)

9

In [71]:
np.max(a,axis=0)

array([8, 9, 6])

In [72]:
np.max(a,axis=1)

array([6, 9, 6])

In [73]:
np.min(a,axis=0)

array([1, 5, 5])

In [74]:
np.min(a)

1

In [75]:
np.min(a,axis=1)

array([1, 5, 2])

In [76]:
np.cumsum(a)

array([ 1,  6, 12, 20, 29, 34, 36, 42, 48])

In [79]:
np.cumsum(a,axis=0)

array([[ 1,  5,  6],
       [ 9, 14, 11],
       [11, 20, 17]])

In [80]:
np.cumsum(a,axis=1)

array([[ 1,  6, 12],
       [ 8, 17, 22],
       [ 2,  8, 14]])

In [81]:
np.argmax(a)

4

In [82]:
np.argmin(a)

0